### ISSUE TITLE
Importing components into .mdx

### ISSUE THREAD

**Issue by selipso** [LekoArts/gatsby-starter-minimal-blog#11]
Hi, thanks for creating this blog template with mdx. I really like it and would like to use it. I'm wondering how you can import plain react components into .mdx files from the 'components' folder. I see the react-live example in one of the posts but I would just like to import a React component into a blog post without showing the code snippet. Thanks in advance!

**Comment by LekoArts** [comment]
You can import the component like normal with `import Component from '../path/to/component'` and then use `<Component />` just somewhere in your MDX file. That's what so is cool about MDX 👍

**Comment by selipso** [comment]
Ah, ok, thanks. I had to make a separate components directory inside the blog because the components from 'src' weren't available for some reason.

**Comment by szarouski** [comment]
Hi LekoArts, another question about importing components. I have similar setup to what you have in this repo, but I run into following issues https://github.com/ChristopherBiscardi/gatsby-mdx/issues/284#issuecomment-464408143 when I either rename or import new components. Do you experience the same?

Thank you.

**Comment by szarouski** [comment]
I played a little bit more with setup and if you keep files under pages folder then hot reloading works. I think that should be enough for my usage, however it would be great to know why there is a difference and if there is a way to configure blog folder to work as if it was under pages folder.

**Comment by szarouski** [comment]
Please ignore, I can see same issues in gatsby-mdx/examples/kitchen-sink project, so it is not an issue with this starter.
