### ISSUE TITLE
Errors on gatsby new & subsequent errors on gatsby develop

### ISSUE THREAD

**Issue by saifalfalah** [LekoArts/gatsby-starter-minimal-blog#12]
On starting a new blog, there is an error:
```
saif@LAPTOP-KUN8OA22:/mnt/c/Users/saifa$ gatsby new blog https://github.com/LekoArts/gatsby-starter-minimal-blog
info Creating new site from git: https://github.com/LekoArts/gatsby-starter-minimal-blog.git
Cloning into 'blog'...
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 611 (delta 16), reused 70 (delta 14), pack-reused 528
Receiving objects: 100% (611/611), 2.24 MiB | 289.00 KiB/s, done.
Resolving deltas: 100% (281/281), done.
success Created starter directory layout
info Installing packages...
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> sharp@0.21.3 install /mnt/c/Users/saifa/blog/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz

> cwebp-bin@5.0.0 postinstall /mnt/c/Users/saifa/blog/node_modules/cwebp-bin
> node lib/install.js

  ⚠ Command failed: /mnt/c/Users/saifa/blog/node_modules/cwebp-bin/vendor/cwebp -version
/mnt/c/Users/saifa/blog/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory


  ⚠ cwebp pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c ./configure --disable-shared --prefix="/mnt/c/Users/saifa/blog/node_modules/cwebp-bin/vendor" --bindir="/mnt/c/Users/saifa/blog/node_modules/cwebp-bin/vendor"
configure: error: in `/tmp/b543b26e-fe73-422e-86bc-35f94ae8dc51':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for style of include used by make... none
checking for gcc... no
checking for cc... no
checking for cl.exe... no

    at Promise.all.then.arr (/mnt/c/Users/saifa/blog/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

> mozjpeg@6.0.1 postinstall /mnt/c/Users/saifa/blog/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> pngquant-bin@5.0.1 postinstall /mnt/c/Users/saifa/blog/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully

> styled-components@4.1.3 postinstall /mnt/c/Users/saifa/blog/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN eslint-config-react-app@3.0.6 requires a peer of babel-eslint@9.x but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-starter-minimal-blog@3.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2098 packages from 1159 contributors and audited 25989 packages in 922.742s
found 0 vulnerabilities
```

And then when you run `gatsby develop` you get:

```
saif@LAPTOP-KUN8OA22:/mnt/c/Users/saifa/blog$ gatsby develop
success open and validate gatsby-configs — 0.019 s
success load plugins — 0.891 s
success onPreInit — 7.177 s
success delete html and css files from previous builds — 0.046 s
success initialize cache — 0.095 s
success copy gatsby files — 1.468 s
success onPreBootstrap — 0.033 s
success source and transform nodes — 1.707 s
success building schema — 1.788 s
success createPages — 0.098 s
success createPagesStatefully — 0.116 s
success onPreExtractQueries — 0.001 s
success update schema — 0.258 s
success extract queries from components — 0.246 s
Generating image thumbnails [==============================] 4/4 0.0 secs 100%
Generating image thumbnails [==============================] 8/8 0.5 secs 100%
error Failed to process image /mnt/c/Users/saifa/blog/blog/2019-01-20/315.jpg


  Error: Command failed: /mnt/c/Users/saifa/blog/node_modules/cwebp-bin/vendor/cwebp -quiet -mt -q 90 -o /tmp/aa093377-49f1-4fcd-bcd8-1f093724462c /tmp/090fb772-4e55-47de-b0c6-f1450c00b9a6
  /mnt/c/Users/saifa/blog/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory

  - index.js:231 Promise.all.then.arr
    [blog]/[exec-buffer]/[execa]/index.js:231:11

  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - async.js:138 _drainQueueStep
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12

  - async.js:131 _drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14


error UNHANDLED REJECTION


  Error: Command failed: /mnt/c/Users/saifa/blog/node_modules/cwebp-bin/vendor/cwebp -quiet -mt -q 90 -o /tmp/aa093377-49f1-4fcd-bcd8-1f093724462c /tmp/090fb772-4e55-47de-b0c6-f1450c00b9a6
  /mnt/c/Users/saifa/blog/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory

  - index.js:231 Promise.all.then.arr
    [blog]/[exec-buffer]/[execa]/index.js:231:11

  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - async.js:138 _drainQueueStep
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12

  - async.js:131 _drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14
```

**Comment by LekoArts** [comment]
Did you install node-gyp? https://github.com/nodejs/node-gyp#installation

**Comment by saifalfalah** [comment]
No. Should I have?

**Comment by LekoArts** [comment]
Yes, this starter uses gatsby-image => gatsby-transformer-sharp => sharp. And sharp needs that installed like mentioned here :) https://github.com/LekoArts/gatsby-starter-minimal-blog#getting-started

**Comment by saifalfalah** [comment]
Installing node-gyp didn't work. `gatsby new` still fails with 

`Command failed: /mnt/c/Users/saifa/Work/blog/node_modules/cwebp-bin/vendor/cwebp -version
/mnt/c/Users/saifa/Work/blog/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory`

And then when I run `gatsby develop` it fails with: 

`success open and validate gatsby-configs — 0.027 s
success load plugins — 0.332 s
success onPreInit — 3.109 s
success delete html and css files from previous builds — 0.007 s
success initialize cache — 0.012 s
success copy gatsby files — 0.738 s
success onPreBootstrap — 0.019 s
success source and transform nodes — 0.824 s
success building schema — 0.782 s
success createPages — 0.057 s
success createPagesStatefully — 0.054 s
success onPreExtractQueries — 0.001 s
success update schema — 0.156 s
success extract queries from components — 0.100 s
Generating image thumbnails [==============================] 4/4 0.4 secs 100%
error Failed to process image /mnt/c/Users/saifa/Work/blog/blog/2019-01-20/315.jpg


  Error: Command failed: /mnt/c/Users/saifa/Work/blog/node_modules/cwebp-bin/vendor/cwebp -quiet -mt -q 90 -o /tmp/55  44a0ee-0cc5-41bc-8ed5-1e12a00075a0 /tmp/fd7b5cb4-1eee-4ba6-88b3-dd55f48c723e
  /mnt/c/Users/saifa/Work/blog/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1:   cannot open shared object file: No such file or directory

  - index.js:231 Promise.all.then.arr
    [blog]/[exec-buffer]/[execa]/index.js:231:11

  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - async.js:138 _drainQueueStep
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12

  - async.js:131 _drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14


error UNHANDLED REJECTION


  Error: Command failed: /mnt/c/Users/saifa/Work/blog/node_modules/cwebp-bin/vendor/cwebp -quiet -mt -q 90 -o /tmp/55  44a0ee-0cc5-41bc-8ed5-1e12a00075a0 /tmp/fd7b5cb4-1eee-4ba6-88b3-dd55f48c723e
  /mnt/c/Users/saifa/Work/blog/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1:   cannot open shared object file: No such file or directory

  - index.js:231 Promise.all.then.arr
    [blog]/[exec-buffer]/[execa]/index.js:231:11

  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - async.js:138 _drainQueueStep
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12

  - async.js:131 _drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14`

**Comment by saifalfalah** [comment]
I'm on WSL so maybe that's the problem. I'm going to install the build-essential and then try.

**Comment by LekoArts** [comment]
Did that work?

**Comment by saifalfalah** [comment]
Unfortunately, it did not. I'll try again and post the exact error codes.

**Comment by szarouski** [comment]
@saifalfalah I'm not sure how helpful it will be, but I also using wsl, so this shouldn't be a problem. I recall seeing issues when installing using first command, but gatsby develop starts ok.

**Comment by saifalfalah** [comment]
Here's the error I'm still getting

`success open and validate gatsby-configs — 0.009 s
success load plugins — 0.315 s
success onPreInit — 2.404 s
success delete html and css files from previous builds — 0.009 s
success initialize cache — 0.039 s
success copy gatsby files — 0.546 s
success onPreBootstrap — 0.015 s
success source and transform nodes — 0.781 s
success building schema — 0.736 s
success createPages — 0.039 s
success createPagesStatefully — 0.040 s
success onPreExtractQueries — 0.000 s
success update schema — 0.119 s
success extract queries from components — 0.087 s
Generating image thumbnails [==============================] 4/4 0.0 secs 100%
error Failed to process image /mnt/c/Users/saifa/Learn/test-lekoArts/blog/2019-01-20/315.jpg


  Error: Command failed: /mnt/c/Users/saifa/Learn/test-lekoArts/node_modules/cwebp-bin/vendor/cwebp -quiet -mt -q 90 -o   /tmp/77e66059-e9a8-4f52-8f31-f966847c27d9 /tmp/54f35f5d-1147-488b-a689-f7ef21a0be8e
  /mnt/c/Users/saifa/Learn/test-lekoArts/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libG  L.so.1: cannot open shared object file: No such file or directory`

**Comment by saifalfalah** [comment]
@szarouski The reason I think this could be due to WSL is because of the error. Maybe the paths aren't converting properly or something...

**Comment by szarouski** [comment]
> Maybe the paths aren't converting properly

I made some changes for WSL setup so drives are mounting at the root too `/c/Users/...`
That is the only WSL customization I added, so it might be a reason why it is working for me. This is how I did that - https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly#ensure-volume-mounts-work

**Comment by LekoArts** [comment]
Closing this issue then as this seems to be an environmental issue, not related to the starter's code.
