### ISSUE TITLE
link to codesandbox results in 502 

### ISSUE THREAD

**Issue by saylestyler** [LekoArts/gatsby-starter-minimal-blog#136]
to reproduce: [go to the project linked in readme](https://codesandbox.io/s/github/LekoArts/gatsby-starter-minimal-blog/tree/master/)

bizarrely works if the project is [forked](https://codesandbox.io/s/gatsby-starter-minimal-blog-oymbm)?

**Comment by LekoArts** [comment]
It was a temporary hiccup
