### ISSUE TITLE
Custom Permalink and Pagination

### ISSUE THREAD

**Issue by mskian** [LekoArts/gatsby-starter-minimal-blog#41]
Hi,

1 - I want to add Custom Permalink For posts and currently It was taken from the post title. I want to Add Custom Permalink for posts.
2 - This theme having Pagination? (if not how to implement?)

**Comment by nidafarooqui** [comment]
I have the same question for implementing pagination. 

I tried doing it on my own but it turned out to be a little more complex than I expected. 

I am not familiar with GraphQL so I could only implement the React portion. Any tips would be greatly appreciated.

**Comment by LekoArts** [comment]
You can learn how to create a pagination on the Gatsby docs: https://www.gatsbyjs.org/docs/adding-pagination/
