### ISSUE TITLE
The link and the text are mixed together and cannot be distinguished. Should the display color of the link be modified?

### ISSUE THREAD

**Issue by liaoyunduo** [LekoArts/gatsby-starter-minimal-blog#9]
The link and the text are mixed together and cannot be distinguished. Should the display color of the link be modified?

**Comment by LekoArts** [comment]
Ah, yeah, good point.
It would be best if the links in the blogpost texts are highlighted (so pages like [this](https://minimal-blog.netlify.com/scittle-luo)).

The style could be modified here:
https://github.com/LekoArts/gatsby-starter-minimal-blog/blob/master/src/templates/post.js#L33
