### ISSUE TITLE
Firefox "SyntaxError: invalid regexp group"

### ISSUE THREAD

**Issue by iceener** [LekoArts/gatsby-starter-minimal-blog#97]
Looks like there's some issue with one of the modules, connected to https://bugzilla.mozilla.org/show_bug.cgi?id=1425763

In fact, starter doesn't work in Firefox.

**Comment by LekoArts** [comment]
Visited the live site with Firefox 67.0.4 and can't reproduce this. Please give more details on how to reproduce this issue. Thanks!

**Comment by iceener** [comment]
![image](https://user-images.githubusercontent.com/29215115/60464246-475a6780-9c4e-11e9-9ead-18a60793873a.png)

@LekoArts just open Console and you'll see the error: "SyntaxError: invalid regexp group".
In my case it's broke app. The only way was to remove Markdown dependencies and switched to Headless CMS.
